launchdarkly/node-server-sdk

index.js
Ignore errors thrown by json-pointer, on invalid update and delete events.
Fixes https://github.com/launchdarkly/node-client/issues/25
=> Ignore errors thrown by json-pointer

index.js, test/test.js
In offline mode no requests are made, so an API key is not strictly necessary. It's convenient to allow no key when the client is interacting with unit tests, or in development.
Since it's easy to work around this I've put a minimal changeset in this PR. If you think it would make a good addition, I'd be happy to add companion tests.
=> Skip the check of an API key when configured to be offline.

feature_store.js
After deleting a flag on production, I got this error:
```
TypeError: Cannot read property 'deleted' of undefined
at Object.InMemoryFeatureStore.store.all (/var/app/current/node_modules/ldclient-node/feature_store.js:31:18)
at EventEmitter.client.all_flags (/var/app/current/node_modules/ldclient-node/index.js:140:26)
at DarklyLaboratory.js:13:16
at new wrappedPromise (/var/app/current/node_modules/newrelic/lib/instrumentation/core/globals.js:133:18)
at DarklyLaboratory.js:12:17
at wrappedPromise.linkTransaction 
```
This is due to an `undefined` value in the flag list. This PR fixes it.
=> Fixed an error in feature_store, if a flag value is undefined

index.js
Previously it was impossible for the 'ready' event to be seen by any listener when in offline mode, because the event was fired before any listener could be attached.
=> Emit listenable 'ready' event when in offline mode

index.js
..caused by effectively calling `setInterval` with an interval of `0`
Closes #44, if merged
=> Fixed high-cpu problem

index.js
This addresses #53 -- we were failing to sanitize non-string user keys in all_flags calls.
=> Sanitize user in all_flags call

eventsource.js, index.js
For errors with known messages, just log out the message. Don't give an Error to winston so it won't print a stack trace. If we have a message, it should be clear where the error came from.
```js
error: [LaunchDarkly] Error: Unexpected error: "message"
at /.../node_modules/ldclient-node/index.js:73:19
at EventSource.es.onerror (/.../node_modules/ldclient-node/streaming.js:19:7)
at emitOne (events.js:96:13)
at EventSource.emit (events.js:188:7)
at _emit (/.../node_modules/ldclient-node/eventsource.js:188:17)
at EventSource.foo (/.../node_modules/ldclient-node/eventsource.js:40:5)
at Object.StreamProcessor.processor.start (/.../node_modules/ldclient-node/streaming.js:86:8)
at Object.new_client [as init] (/.../node_modules/ldclient-node/index.js:64:22)
at Object.<anonymous> …
```
=> Log short errors for known errors

index.d.ts
Definition did not line up with implementation.
cc @natebrennand
ref: https://github.com/launchdarkly/node-client/pull/60
=> Remove user from init typescript definition

index.d.ts
Sorry, I didn't quite do my due diligence before opening #62. Found 3 more small things.
=> type def fixes

index.d.ts
Fixes
```
> tsc
node_modules/ldclient-node/index.d.ts(311,31): error TS7006: Parameter 'err' implicitly has an 'any' type.
```
=> Fix type defs (implicit any)

evaluate_flag.js
Fixes "Cannot read property 'constructor' of undefined" TypeError when user attributes are `undefined`.
See also #51
=> Support `undefined` user attributes

README.md
Just updating docs to use `variation` instead of deprecated `toggle`.
=> Use `variation` instead of deprecated `toggle`

CHANGELOG.md, package.json, redis_feature_store.js, test/feature_store_test_base.js, test/redis_feature_store-test.js
- In the Redis feature store, fixed synchronization problems that could cause a feature flag update to be missed if several of them happened in rapid succession.
=> prepare 4.0.2 release

CHANGELOG.md, index.js, package.json
- Fixed a [bug](https://github.com/launchdarkly/node-client/issues/85) that would cause an unhandled promise rejection warning-- and, depending on your Node configuration, a crash-- if there was an HTTP error during an automatic event flush.
=> prepare 4.0.3 release

CHANGELOG.md, event_processor.js, event_summarizer.js, package-lock.json, package.json, test/event_summarizer-test.js
- Fixed a bug that caused summary events to combine two different counters: a) flag evaluations that produced the flag's first variation, and b) counts for flag evaluations that fell through to the default value.
- Removed debug-level logging that was listing every analytics event.
=> prepare 5.0.1 release

index.d.ts
- added missing private fields related configuration options
- added missing user keys buffer configuration options
Description taken from https://docs.launchdarkly.com/docs/node-sdk-reference site.
=> updated typescript definitions for LDOptions

index.d.ts, package-lock.json, package.json
- Now outputs a more descriptive log message if `allFlags` is called with a null user object. (Thanks, [jbatchelor-atlassian](https://github.com/launchdarkly/node-client/pull/103)!)
- Added TypeScript definitions for some previously undefined types.
- Updated `request` package dependency to `2.87.0`, to avoid a [security vulnerability](https://snyk.io/vuln/npm:cryptiles:20180710) in a package used by `request`.
=> prepare 5.1.1 release

CHANGELOG.md, README.md, package-lock.json, package.json
- Removed a dependency on the deprecated [`crypto`](https://www.npmjs.com/package/crypto) module. ([#92](https://github.com/launchdarkly/node-client/issues/92))
=> prepare 5.1.2 release

index.js
It's best to resolve promises with the object that the user expects. This way in an async/await world, the value resolved can be assigned to a var:
```
const ldclient = await ldClient.waitForInitialization();
console.log(await ldclient.allFlags(<user>));
```
In the current version, the above code would yield a `null` or `undefined` value for `ldclient`.
=> `waitForInitialization()` should resolve with the client

event_summarizer.js
This can cause errors in Mocha tests. 
```global leak detected: counterOut```
=> Remove global variable from event_summarizer

index.js
The error reporter was being called with a `variationErr`, which in two cases did not exist as the error had been named `err` instead. This was causing `uncaughtException: variationErr is not defined` to crash my application if `variation` was called before the SDK had finished initialising.
=> Fix uncaught 'variationErr is not defined' exception

configuration.js, test/configuration-test.js
Hello,
We tried upgrading to v5.6.1 (from 3.4.0) of the client today and ran into an issue with retrieving all of our features. Our app retrieves features from 4 different LD projects and we were noticing that only the features from a single project were coming back. Debugging into this, the root cause is that all 4 of our LD client instances are using the same `featureStore` object. If we adjust the configuration object to create a new `InMemoryFeatureStore` each time defaults are applied, as I've done in this PR, the issue goes away.
If these changes are desirable, another possible solution would be to export `InMemoryFeatureStore` just like `RedisFeatureStore` so consumers that need to use multiple clients can do something like this:
```js
let ldClient = LaunchDarkly.init(sdkKey, { …
```
=> ensure the default config does not share the featureStore

evaluate_flag.js
This is particularly important when running with `--use-strict`
=> Properly define the variable.

index.d.ts
The implementation of feature-store only has 3 parameters and key is accessed through data.key
=> Upsert type signature is wrong
